 const About =()=>{
    return(
        <div>
           Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla aliquam nec magna ac interdum. Phasellus cursus efficitur dui quis iaculis. Proin a metus ut neque rutrum vulputate sit amet quis urna. Nam non diam tempor, convallis tortor eget, rhoncus nulla. Curabitur odio massa, tempus cursus facilisis quis, imperdiet nec neque. Duis euismod nibh ultrices, posuere dui quis, euismod mauris. Donec molestie consectetur nunc, vel sagittis erat hendrerit nec. Suspendisse viverra purus nisi, sed auctor turpis venenatis nec.

Curabitur et libero vitae lacus accumsan accumsan ac et tortor. Proin consectetur blandit placerat. Aenean consectetur semper eros in consectetur. Duis turpis enim, interdum eu diam vitae, fringilla cursus purus. Vivamus tincidunt risus eu nisl mollis molestie. Integer iaculis, nisl et aliquet pharetra, purus magna porttitor nulla, at posuere lorem ante et urna. Suspendisse mollis, mauris et feugiat pretium, eros est congue urna, at faucibus enim libero sit amet risus. Nulla ultricies finibus ultrices. Morbi imperdiet lobortis vehicula. Nunc tempus quis nisi sit amet accumsan.

Aenean commodo magna eros, eget iaculis dui viverra vel. Fusce sagittis ultrices mattis. Vestibulum sodales lectus elit, eget feugiat velit cursus quis. Ut non auctor diam, ac mollis felis. Donec et faucibus eros. Vivamus metus velit, pulvinar vel imperdiet vel, dapibus non felis. Curabitur nec porttitor orci. Ut rhoncus tortor nec urna accumsan, sit amet tincidunt elit efficitur. Etiam facilisis luctus feugiat. Donec dapibus mauris sit amet lorem malesuada, vitae dignissim ante aliquet.

Nam ultricies ligula vitae est vulputate auctor. Sed scelerisque lacus a libero convallis, ut aliquet erat venenatis. Nullam mollis sem in ipsum faucibus, rutrum porttitor nulla luctus. Fusce tempus varius ex eu vehicula. Praesent porta molestie urna sit amet tincidunt. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec non viverra enim. Maecenas quis consectetur arcu. Nunc tempus efficitur leo in accumsan. Nam porttitor mattis diam. Quisque condimentum tempor ornare. Phasellus dictum purus a porttitor volutpat. Curabitur a dui tempus mi accumsan vulputate ut a ante.

Morbi dui magna, lacinia ut nunc vitae, pretium imperdiet arcu. Curabitur lacinia magna pulvinar, pellentesque est ac, malesuada mi. Etiam scelerisque nunc vitae tellus congue, eu posuere mi accumsan. Donec aliquet aliquam risus sit amet hendrerit. Proin interdum interdum dapibus. Pellentesque luctus turpis massa, id egestas nibh pellentesque eget. Vestibulum vehicula nec arcu non rutrum. Aliquam erat volutpat. Donec diam est, euismod at enim vel, malesuada consectetur dolor. Duis fringilla, tellus nec elementum feugiat, risus metus pellentesque orci, ac tempus mauris nisl eget mi. Sed viverra nulla vel dignissim convallis. Interdum et malesuada fames ac ante ipsum primis in faucibus.

Donec commodo convallis blandit. Phasellus vitae velit vitae nulla vulputate sollicitudin a vitae magna. Curabitur euismod tristique ipsum eu pretium. Ut nibh est, fermentum in ante ac, pretium feugiat mi. Cras ligula libero, fermentum nec cursus non, malesuada sed lorem. Nulla sodales mauris elementum accumsan pellentesque. Aliquam a magna vulputate massa dignissim iaculis ac quis quam. Vivamus nisi erat, pellentesque vitae tincidunt nec, vulputate vel mauris. Proin commodo, risus vel porta sollicitudin, sem erat molestie ante, vel sollicitudin sapien nulla eu justo. Nunc dui turpis, imperdiet et tortor ut, malesuada venenatis nibh. Donec nisl orci, consequat quis massa sed, suscipit placerat massa. Nullam vitae velit nunc. Aliquam nec vulputate elit, maximus consequat massa.

Maecenas in vehicula odio. Suspendisse semper, justo a sagittis aliquet, diam metus viverra augue, et tincidunt lectus felis id arcu. Fusce dapibus convallis risus, in gravida libero fermentum in. Quisque vel nisl non nunc malesuada vulputate sit amet eget ante. Fusce placerat venenatis consequat. Nam eget sollicitudin eros. Cras mollis condimentum tellus, at fringilla purus vestibulum vel. Praesent nulla est, tincidunt vitae risus a, pellentesque gravida diam. Phasellus posuere urna ut lacus vestibulum dictum. Etiam interdum ornare libero eget dapibus.

Phasellus libero arcu, ultricies ac sapien at, egestas feugiat augue. In eget pharetra nisl. Phasellus ut hendrerit augue. Nunc lacinia, ante laoreet pharetra ullamcorper, tellus libero pharetra orci, ut accumsan sapien nisl nec massa. Proin feugiat velit ac diam auctor luctus. Etiam ut justo metus. Vivamus eleifend nibh lacus, non dapibus lorem finibus ut. Aenean et nulla non mi malesuada consequat non hendrerit nunc. Sed tortor risus, blandit nec sollicitudin non, tincidunt eu diam. Curabitur felis leo, efficitur a mauris sit amet, porttitor feugiat dui. Sed enim nisl, facilisis nec erat consequat, dapibus vestibulum felis.

Vivamus justo ante, lobortis ac placerat nec, lobortis in enim. In ultricies tempor leo a ultricies. Sed quis laoreet justo. Vivamus accumsan, magna et venenatis iaculis, tellus mauris tincidunt ex, id pharetra massa nisl vel quam. Donec aliquet ligula vel eleifend congue. Nunc eu nisl non metus pretium pellentesque. Etiam accumsan efficitur pharetra. Nulla pretium porttitor vulputate. Integer eleifend tristique dolor, ut ultricies augue aliquet sit amet. Integer feugiat nec nulla vitae imperdiet. Vivamus sagittis eleifend sem sed volutpat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In pulvinar magna at erat tristique, molestie bibendum ligula accumsan.

Vivamus efficitur turpis quis nisl tempus volutpat. Aenean quis nulla eu nisi eleifend aliquam et ac arcu. Phasellus aliquet tempus lorem, a commodo lectus placerat id. Vivamus non diam a ipsum feugiat suscipit vel non dui. Vivamus tempus orci ac turpis faucibus, at commodo diam laoreet. Sed sit amet purus enim. Aliquam tincidunt nec nisl sed posuere. Ut mattis tempus dui, eu faucibus erat viverra consectetur. Phasellus vehicula posuere egestas.

Ut ut purus justo. Donec ut malesuada justo. Etiam ultrices, sapien non blandit faucibus, enim lacus molestie dolor, quis scelerisque libero odio id turpis. Ut sodales laoreet orci quis consequat. Vivamus orci risus, laoreet id lorem vel, aliquam hendrerit nunc. Sed vitae dui vel ex lacinia viverra. Curabitur quis magna id nisl blandit vestibulum. Nulla facilisi. Nulla facilisi. Vivamus auctor in odio non elementum. Praesent vel gravida ante.

Morbi mattis sem tortor, quis eleifend ipsum maximus nec. Sed vestibulum tellus felis, quis finibus augue aliquam eget. Aliquam erat volutpat. Nulla mollis consequat nisi, in elementum sem viverra et. Nulla ut ex ac nibh viverra tincidunt. Fusce quis fermentum ante. Aliquam imperdiet non lacus a rhoncus. Integer venenatis porta tellus sed tempus.

Sed vulputate sagittis sollicitudin. Nam quis augue nulla. Curabitur sed lacus malesuada, ultricies mi sit amet, rhoncus justo. Etiam dignissim vulputate nisl, nec aliquam diam dictum quis. Sed porta eros tempus ante consequat, vel commodo magna molestie. Maecenas finibus vitae orci sit amet porta. Nunc ultrices libero vel elit luctus, id hendrerit lectus ultrices. Proin sapien dolor, auctor placerat feugiat eget, elementum eu augue. Vivamus eu felis eu erat molestie ultrices id nec tellus. In faucibus congue consequat. Phasellus gravida suscipit neque non finibus.

Donec porttitor sapien eu semper tempus. Ut viverra velit pretium nisi euismod, sit amet vehicula enim hendrerit. Nunc lacus augue, fermentum eu venenatis non, ullamcorper a sem. Vestibulum ut libero id quam finibus gravida a lacinia lacus. Pellentesque auctor efficitur risus at efficitur. Ut a leo sed ligula convallis lacinia. Vestibulum interdum lacus scelerisque, pulvinar augue id, lobortis arcu. Phasellus eros augue, venenatis non accumsan ac, tempor eu lectus. Duis elementum odio massa, a mattis dolor ultrices eget. Vivamus mollis leo id consectetur elementum. In eu commodo augue. Fusce consequat nulla ut odio pulvinar, eget tincidunt erat congue. Nulla facilisi.

Proin vel est magna. Nunc sem dolor, aliquet vitae dignissim posuere, malesuada in enim. Sed vitae metus porttitor, auctor neque ut, tincidunt dolor. Cras pellentesque convallis turpis, a maximus mi sodales in. Morbi placerat euismod diam ac porttitor. Morbi congue varius dapibus. Vestibulum felis mauris, dignissim in feugiat in, viverra porta erat. Morbi pharetra enim lacus, et gravida metus ullamcorper vel. Integer ut cursus felis.

Praesent sem nisl, tristique eget facilisis quis, semper non diam. Aliquam accumsan arcu nec ullamcorper dictum. Quisque tristique erat eget rutrum accumsan. Sed dictum nulla magna, at pulvinar arcu pulvinar in. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis vel lacus et libero fermentum eleifend nec sit amet nisi. Praesent et tempus ipsum.

Donec eleifend nulla quis mi ullamcorper, sit amet hendrerit justo molestie. Vivamus gravida semper velit, et fringilla urna ultrices sed. Aenean consequat varius sapien, non porttitor diam congue at. Maecenas tempus tortor arcu, non ultrices lacus cursus nec. Vestibulum lobortis magna egestas, maximus est pretium, rhoncus ligula. Fusce ac metus eleifend, feugiat sem sed, egestas metus. Sed egestas ligula a nisl posuere efficitur. Sed a enim id urna semper consectetur. Duis sollicitudin efficitur commodo. Nam diam quam, ultricies a ultrices et, luctus sit amet magna. Morbi dictum metus vitae blandit placerat. Etiam quam velit, dictum in vulputate id, finibus at enim. Phasellus vulputate diam in nisi aliquam molestie. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi vel libero turpis. Nulla id erat in mi dapibus ultricies id quis leo.

Phasellus placerat a purus volutpat sollicitudin. Vivamus egestas sagittis purus finibus malesuada. Nullam a est mattis, tristique mauris sit amet, porta leo. Vivamus imperdiet dui risus, consequat cursus leo rhoncus sit amet. Aliquam vel enim tellus. Integer eget sodales est, efficitur bibendum augue. Fusce blandit nisi sed velit gravida finibus. Praesent blandit felis in est vehicula mollis. Fusce faucibus sagittis malesuada. Mauris sit amet faucibus turpis, eget iaculis neque. Donec augue quam, tincidunt id venenatis ac, imperdiet id lectus.

Integer iaculis, libero vitae luctus pretium, quam purus rhoncus nunc, luctus imperdiet eros dui id leo. Morbi rhoncus tincidunt volutpat. Phasellus quam sem, rhoncus at blandit id, lacinia a neque. In quis metus tellus. Pellentesque elementum venenatis ligula nec luctus. Morbi nec sodales urna, sagittis tempus odio. In scelerisque placerat fermentum. Duis viverra malesuada ante ac sollicitudin. Vestibulum tincidunt, nibh sit amet lobortis tincidunt, magna odio vestibulum nibh, a dictum dui ligula id erat. Nunc fermentum enim quis ipsum hendrerit tincidunt. Fusce quis semper justo.

Curabitur vulputate quis est vel pretium. Nullam sollicitudin metus id ante convallis, non pulvinar velit suscipit. Aliquam dui turpis, maximus quis interdum in, fringilla sit amet nibh. Vestibulum vel leo aliquam, cursus augue ut, scelerisque ex. Cras porttitor at quam laoreet tempus. Nam mattis ipsum felis, vel pretium sem auctor in. Vivamus hendrerit accumsan risus, eget ultrices magna dapibus a. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus vitae viverra velit. Ut vitae turpis ex. Vestibulum faucibus justo in neque dictum, nec tempus odio condimentum. Quisque sollicitudin justo sit amet ligula elementum, a tristique nunc mattis.
        </div>
    )
}
export default About;